### ISSUE TITLE
aikup can't install aiken v1.0.29-alpha

### ISSUE THREAD

**Issue by Quantumplation** [aiken-lang/aikup#8]
#### What Git revision are you using? 
N/A
#### What operating system are you using, and which version?

- [ ] Linux / Ubuntu
- [X] Linux / Other
- [ ] macOS
- [ ] Windows

#### Describe what the problem is? 
```sh
$ aikup install v1.0.29-alpha


================================================================================

░█▀▀▄░▀█▀░▒█░▄▀░▒█▀▀▀░▒█▄░▒█             Modern and modular toolkit
▒█▄▄█░▒█░░▒█▀▄░░▒█▀▀▀░▒█▒█▒█       for Cardano Smart Contract development.
▒█░▒█░▄█▄░▒█░▒█░▒█▄▄▄░▒█░░▀█                 Written in Rust.

================================================================================

Repo       : https://github.com/aiken-lang/aiken
Docs       : https://aiken-lang.org/
Chat       : https://discord.gg/Vc3x8N9nz2
Contribute : https://github.com/aiken-lang/aiken/blob/main/CONTRIBUTING.md

================================================================================
aikup: installing aiken (version v1.0.29-alpha, tag v1.0.29-alpha)
aikup: downloading aiken
####################################################################################################### 100.0%
tar: Error opening archive: Unrecognized archive format
aikup: installed - aiken v1.0.28-alpha+c9a1519
aikup: done
```

In particular, notice that it fails to unpack the archive, but still reports that it was succesful; after this, aiken is still v1.0.28

#### What should be the expected behavior?
Correctly install v1.0.29; report an error if we failed to install a new version of aiken

**Comment by rvcas** [comment]
highly likely you are using the old bash script by accident

**Comment by Quantumplation** [comment]
Yes, can confirm i have the bash version installed;

However, it's the version that's installed by aikup as described here:

https://aiken-lang.org/installation-instructions; when I try to upgrade it, I get:

```
Warning: aiken-lang/tap/aikup 0.0.10 already installed
```

So perhaps you need to release a new brew formula?

**Comment by rvcas** [comment]
just delete `$HOME/.aiken/bin/aikup`
